### ISSUE TITLE
terminate called after throwing an instance of 'IconImageManager::IOException'

### ISSUE THREAD

**Issue by saskra** [abria/TeraStitcher#79]
I am using this version: https://github.com/abria/TeraStitcher/wiki/Binary-packages#terastitcher-installer-gui-version

When I wanted to execute step 8 of the Command-line demo (https://github.com/abria/TeraStitcher/wiki/Demo-and-batch-scripts#command-line-demo) I got this error:

```shell
OPERATION:	Multiresolution tile generation
PHASE:		Initializing...
TIME REMAINING:	0 minutes and 0 seconds
PROGRESS:	0%	::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

terminate called after throwing an instance of 'IconImageManager::IOException'
Cancelled (memory dump written)

```

**Comment by iannellog** [comment]
Even this issue could be due to the use of the version using bioformats.
 Another user had the same problem. Here is what he wrote after solving the problem:

"I finally figured out that my error was due to the wrong loading of the shared library "libjvm.so".
I changed the path of my "jre" and the problem was solved.
I am now able to merge the tiles correctly."

I hope this can help.

**Comment by saskra** [comment]
Thanks, then I will try a version without Bioformats.
