### ISSUE TITLE
ERROR: in StackStitcher::computeDisplacements(): incorrect subdata selection

### ISSUE THREAD

**Issue by kannanuv** [abria/TeraStitcher#9]
I got the following error when stitching a dataset scanned using a LaVision Biotechnology UltraII scope.

ERROR: in StackStitcher::computeDisplacements(): incorrect subdata selection [840,850] along Z

is there a work around to stitching this dataset?

**Comment by abria** [comment]
Which dataset?

Please, provide all the information you can so that I can help figuring out what is the problem. E.g, what are the dimensions of your image? What tool are you using (GUI or command line)? Which parameters for stitching? Can you attach the `xml_import.xml` generated by TeraStitcher in the Import step?

Thanks.

**Comment by kannanuv** [comment]
This was caused by running the program in command line with an incomplete dataset. Once all tiles in the dataset was copied the stitching completed correctly.

**Comment by abria** [comment]
Nice, then I will close this issue.
